### ISSUE TITLE
Add identity icon

### ISSUE THREAD

**Issue by wilstenholme** [baxter-cs/baxterite#6]
<h1>Baxterite</h1>

![baxterite-200](https://cloud.githubusercontent.com/assets/14347683/15797416/662dca14-29e5-11e6-97aa-495285cbcd47.png)
![baxterite](https://cloud.githubusercontent.com/assets/14347683/15797354/950a8924-29e2-11e6-91df-4673fa3d27ee.png)

**Comment by jyan-zarate** [comment]
Great job
